spring:
  application:
    name: ms-chatbot-openAi
  config:
    import: optional:application-secrets.yml


server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
