services:
  eureka-server:
    image: lucas607/monify-eureka-server:latest
    build: ./monify-eureka-server
    container_name: ms-eureka-server
    networks:
      - app-network

  ms-users:
    image: lucas607/monify-ms-users:latest
    build: ./ms-users
    container_name: ms-users
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-chatbot-openai:
    image: lucas607/monify-ms-chatbot-openai:latest
    build: ./ms-chatbot-openAi
    container_name: ms-chatbot
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-finance-monify:
    image: lucas607/monify-ms-finance-monify:latest
    build: ./ms-finance-monify
    container_name: db_monify
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-monify-gateway:
    image: lucas607/monify-ms-monify-gateway:latest
    build: ./ms-monify-gateway
    container_name: ms-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-whatsapp:
    image: lucas607/monify-ms-whatsapp:latest
    build: ./ms-whatsapp
    container_name: ms-whatsapp
    depends_on:
      - eureka-server
      - wppconnect-server
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: monify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network


  wppconnect-server:
    image: lucas607/wpp-connect:monify-configs
    build: ./wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: yarn dev
    ports:
      - "21465:21465"
    environment:
      - SECRET_KEY=thismykey
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
