services:
  eureka-server:
    image: lucas607/monify-eureka-server:latest
    build: ./monify-eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  ms-users:
    image: lucas607/monify-ms-users:latest
    build: ./ms-users
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-chatbot-openai:
    image: lucas607/monify-ms-chatbot-openai:latest
    build: ./ms-chatbot-openAi
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-finance-monify:
    image: lucas607/monify-ms-finance-monify:latest
    build: ./ms-finance-monify
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-monify-gateway:
    image: lucas607/monify-ms-monify-gateway:latest
    build: ./ms-monify-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-whatsapp:
    image: lucas607/monify-ms-whatsapp:latest
    build: ./ms-whatsapp
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: monify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  wpp-data:
  pgdata:

networks:
  app-network:
    driver: bridge
