services:
  eureka-server:
    build: ./monify-eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  ms-users:
    build: ./ms-users
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-chatbot-openai:
    build: ./ms-chatbot-openAi
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-finance-monify:
    build: ./ms-finance-monify
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  ms-monify-gateway:
    build: ./ms-monify-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-whatsapp:
    build: ./ms-whatsapp
    ports:
      - "8081:8081"
    depends_on:
      - wppconnect
      - eureka-server
    networks:
      - app-network

  wppconnect:
    image: wppconnect/server-cli:latest
    container_name: wppconnect
    ports:
      - "21465:21465"
    environment:
      - PORT=21465
      - DEBUG=true
      - SECRET_KEY=123123
    volumes:
      - wpp-data:/usr/app/tokens
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: monify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  wpp-data:
  pgdata:

networks:
  app-network:
    driver: bridge
