services:
  eureka-server:
    build: ./monify-eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  ms-users:
    build: ./ms-users
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-chatbot-openai:
    build: ./ms-chatbot-openAi
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-finance-monify:
    build: ./ms-finance-monify
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-monify-gateway:
    build: ./ms-monify-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ms-whatsapp:
    build: ./ms-whatsapp
    ports:
      - "8081:8081"
    depends_on:
      - wppconnect
      - eureka-server
    networks:
      - app-network

  wppconnect:
    image: wppconnect/server-cli:latest
    container_name: wppconnect
    ports:
      - "21465:21465"
    environment:
      - PORT=21465
      - DEBUG=true
      - SECRET_KEY=123123
    volumes:
      - wpp-data:/usr/app/tokens
    networks:
      - app-network

volumes:
  wpp-data:


networks:
  app-network:
    driver: bridge
