FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src


RUN mvn clean install -DskipTests


FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY --from=build /app/target/ms-finance-monify-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8083

CMD ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
